image: Visual Studio 2017
version: 1.0.{build}
skip_branch_with_pr: true
branches:
  only:
  - 3.0
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test:
  categories:
    except:
    - Integration
